[package]
name = "vane"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_app = "0.16.1"
bevy_asset = "0.16.1"
bevy_ecs = "0.16.1"
bevy_math = "0.16.1"
bevy_reflect = "0.16.1"
bevy_render = "0.16.1"
tracing = "0.1.41"
